language: java

deploy:
  provider: lambda
  function_name: ynabPoller
  region: eu-west-2
  role: 'arn:aws:iam::053105132499:role/service-role/ynabPollerRole '
  runtime: java8
  handler_name: uk.co.tombryant.ynab.poller.Handler::handleRequest
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  access_key_id: $AWS_ACCESS_KEY_ID

env:
  global:
  - secure: RO9GVUO4KeM56MGzQ5H5/67RTREgrSKTaxiwYHiBOw+GAPsvwCe0cbdR/qaR3pdg1p8usegMinteWhSH9XnMExe5fhsBY8UTyav0xDv4WJGyKt7pBd/W8y/QVs9V98z/N64ML7bXS6n0Hh3HVhVPZ+pg60tmbM2KKXh1aWz1RuLPETjKya3XLbdWeh/FIpEKAUUvzLz4AoYlrWbUWVh7iqR1O6fle8ijlWj7pG55pmj3CsA3nhvHIepmm5oq3LvrAISquprRf1JJbBwJNKt6I743tWWD0VJe3VUN1NBRLqvegE9dVL+HasGXDt+37CG/nTtx+rMkkwkkBB+T2t20cjbpK/SbjYsKvBLDAQrTbYvo66pB5UPX/JyeeMbdga286cGHoyM6HQviNgvPv5VndIFc2KFdwRzHZUbpB/rkWXkQc4DDD/70Py9WV3wKSh77iVCf5HwJDFgjMvL+ZJdX3zBnwP4mzTtA6VJLkf3b99wq2FfhpLrcg0o44xZ928UfPCQA91Hj3wBtCFfycPFd6l5KOTTl3Op2EeZ//sjyP7mZsp0TdPUK3Bv13QD2eOa0+xHH2UHBzX74QKY6BZ9CFZpYAGR2iTLKjNw0OGw0tTQ2/MSkLk7AcaFvagJPwO735eu9kM9mOZ7tuW3gf2gP2TRxBgDB19cw2cb9U2SvUZk=
  - secure: d+0KwXuFaXkbcbRkLcR+DDNHoJ7MP5DQ7Mklab8/CqWhbd6GPBycaVhUQPB+jkTjuLHlTmZR9xKIRLsTgLJYCNFAlPF0pJDe/hMRdw65NF0ajNnfy20++EYF5Ho3Ec51Vas6vPkvMdoGQRglZdh0xYtOGH+qhJbpsQ3Ig3pJU3jxfQghglPvUpnjcbdTl4fWJr74BynaMyGdzDb210Z271juF2H2Ja6Oju9sJtg9uuVcG75aWmW3QqPtqZqGI3dyatZOkh/gIOgtjgQnZU/8Rlj/REjei0Ds4mMA9glHQvFqdrXkTufyPskB0jnjHiHwb1D/k50AY9r8cnGD9MXmauBez/FvnMcPnBI4tG1rsNRrdSDhsOqtXtYYHekT5dieUuSZUhSdV5waYqMDa1ofjmf7xHIh3ky/Scc8Zh0xKnP5mcmTvHJMVC5Z+DAMla7ptjD6EGABd6Rqu/83JlekrGGS014NsB18o2uhVXFE6PYPAClj8VQgI9L/nijjOf5UGH5lFyGUAJnk5kV+LfXDVBuIkR/BTq7q3k3lLPtnBLAbgf4uVScIgTZRSJTqAI4mutMhwHiezki0iSprvw7N7bdyhTWGDW+srnXtGIK70VsJLyeV874zToCUiVWcNmpSlXWXHm3tHCfp2/UohXTC3cxPF0rgsQeF9aGxYcsJ4lk=
